# Generated by Django 4.1.7 on 2024-03-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestlog',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='requestlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='page_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
