# Generated by Django 4.1.7 on 2024-03-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_page_userinteraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinteraction',
            name='time_spent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
