# Generated by Django 4.1.7 on 2024-03-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_alter_userinteraction_time_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinteraction',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
