# Generated by Django 5.0.3 on 2024-04-01 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_historicaluserinteraction_browser_and_more'),
        ('auths', '0075_alter_address_user_alter_cart_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluserinteraction',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='auths.customuser'),
        ),
        migrations.AlterField(
            model_name='historicaluserloginlog',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='auths.customuser'),
        ),
        migrations.AlterField(
            model_name='userinteraction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auths.customuser'),
        ),
        migrations.AlterField(
            model_name='userloginlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auths.customuser'),
        ),
    ]
