# Generated by Django 4.1.7 on 2024-03-02 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0010_rename_category_categorys_alter_product_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorys',
            new_name='Category',
        ),
    ]
