# Generated by Django 4.1.7 on 2024-03-02 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0012_remove_product_user_alter_product_image2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='model',
            new_name='model_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
