# Generated by Django 4.1.7 on 2024-03-02 14:33

import auths.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0014_category_product_user_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to=auths.models.product_image_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=auths.models.product_image_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=auths.models.product_image_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=auths.models.product_image_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to=auths.models.product_image_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to=auths.models.product_image_path),
        ),
    ]
