# Generated by Django 4.1.7 on 2024-03-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0015_alter_product_image_alter_product_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='folder_name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
