# Generated by Django 4.1.7 on 2024-03-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0021_product_color_alter_order_oderid_alter_order_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deliverycharges',
            field=models.CharField(default='Free', max_length=5),
        ),
    ]
