# Generated by Django 4.1.7 on 2024-03-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0022_product_deliverycharges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='deliverycharges',
            field=models.CharField(default='Free', editable=False, max_length=5),
        ),
    ]
