# Generated by Django 4.1.7 on 2024-03-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0024_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='num_views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
