# Generated by Django 4.1.7 on 2024-03-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0025_product_num_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
