# Generated by Django 4.1.7 on 2024-03-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0026_remove_customuser_name_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, default='User', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, default='User', max_length=100),
        ),
    ]
