# Generated by Django 4.1.7 on 2024-03-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0030_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first',
            field=models.CharField(blank=True, default='first_name', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
