# Generated by Django 4.1.7 on 2024-03-22 21:00

import auths.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0032_remove_customuser_first_alter_customuser_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to="profiles"),
        ),
    ]
