# Generated by Django 4.1.7 on 2024-03-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0035_remove_customuser_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='oderid',
            new_name='order_id',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('PR', 'Processing'), ('C', 'Completed'), ('CA', 'Cancelled')], default='P', max_length=2),
        ),
    ]
