# Generated by Django 4.1.7 on 2024-03-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0037_cart_created_at_cart_updated_at_cartitem_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expected_deliver_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Processing', max_length=20),
        ),
    ]
