# Generated by Django 4.1.7 on 2024-03-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0038_order_expected_deliver_date_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Delivered', 'Completed'), ('Cancelled', 'Cancelled')], default='Processing', max_length=20),
        ),
    ]
