# Generated by Django 4.1.7 on 2024-03-26 16:32

import auths.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0043_temporarytransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarytransaction',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='temporarytransaction',
            name='transaction_id',
            field=models.CharField(blank=True, default=auths.utils.generate_order_number, max_length=100, null=True),
        ),
    ]
