# Generated by Django 4.1.7 on 2024-03-26 16:55

import auths.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0044_temporarytransaction_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarytransaction',
            name='order_id',
            field=models.CharField(blank=True, default=auths.utils.generate_order_number, max_length=100, null=True),
        ),
    ]
