# Generated by Django 4.1.7 on 2024-03-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0045_temporarytransaction_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarytransaction',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
