# Generated by Django 4.1.7 on 2024-03-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0046_alter_temporarytransaction_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paypal_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
