# Generated by Django 4.1.7 on 2024-03-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0048_order_address_alter_order_user_alter_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_promotion_discount',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
    ]
