# Generated by Django 4.1.7 on 2024-03-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0054_attachment_supportticket_historicalsupportticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='support_tickets', to='auths.attachment'),
        ),
    ]
