# Generated by Django 4.1.7 on 2024-03-28 18:12

import auths.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0058_alter_historicalsupportticket_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsupportticket',
            name='reference_id',
            field=models.CharField(blank=True, default=auths.utils.generate_reference_id, editable=False, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='reference_id',
            field=models.CharField(blank=True, default=auths.utils.generate_reference_id, editable=False, max_length=20, null=True),
        ),
    ]
