# Generated by Django 5.0.3 on 2024-03-31 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0061_customuser_seller_historicalcustomuser_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='historicalcustomuser',
            name='seller',
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gstin', models.CharField(max_length=100)),
                ('registered', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
