# Generated by Django 5.0.3 on 2024-04-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0067_alter_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='order_promotion_discount',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_promotion_discount',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
