# Generated by Django 5.0.3 on 2024-04-01 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0070_remove_historicalorder_address_remove_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.RemoveField(
            model_name='address',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='landmark',
        ),
        migrations.RemoveField(
            model_name='address',
            name='line1',
        ),
        migrations.RemoveField(
            model_name='address',
            name='line2',
        ),
        migrations.RemoveField(
            model_name='address',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='address',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
        migrations.RemoveField(
            model_name='historicaladdress',
            name='city',
        ),
        migrations.RemoveField(
            model_name='historicaladdress',
            name='country',
        ),
        migrations.RemoveField(
            model_name='historicaladdress',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='historicaladdress',
            name='landmark',
        ),
        migrations.RemoveField(
            model_name='historicaladdress',
            name='line1',
        ),
        migrations.RemoveField(
            model_name='historicaladdress',
            name='line2',
        ),
        migrations.RemoveField(
            model_name='historicaladdress',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='historicaladdress',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='historicaladdress',
            name='state',
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='address',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='auths.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auths.address'),
        ),
    ]
