# Generated by Django 5.0.3 on 2024-04-01 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0071_remove_address_city_remove_address_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='address', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
