# Generated by Django 5.0.3 on 2024-04-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0072_alter_address_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.RemoveField(
            model_name='historicaladdress',
            name='user',
        ),
        migrations.AddField(
            model_name='address',
            name='full_name',
            field=models.CharField(default='F', max_length=100),
        ),
        migrations.AddField(
            model_name='historicaladdress',
            name='full_name',
            field=models.CharField(default='F', max_length=100),
        ),
    ]
