# Generated by Django 5.0.3 on 2024-04-01 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0075_alter_address_user_alter_cart_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='full_name',
            field=models.CharField(default=' ', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicaladdress',
            name='full_name',
            field=models.CharField(default=' ', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalseller',
            name='registered',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='registered',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL),
        ),
    ]
