# Generated by Django 5.0.3 on 2024-04-01 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0078_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
