# Generated by Django 5.0 on 2024-04-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0079_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalseller',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
