# Generated by Django 5.0.4 on 2024-04-04 20:48

import auths.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0082_alter_historicalseller_user_alter_seller_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='product_id',
            field=models.CharField(blank=True, default=auths.utils.generate_product_id, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(blank=True, default=auths.utils.generate_product_id, max_length=30, null=True),
        ),
    ]
