# Generated by Django 5.0.4 on 2024-04-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0083_historicalproduct_product_id_product_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='label_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='label_generated',
            field=models.BooleanField(default=False),
        ),
    ]
